title: "Martin Haslberger"
description: "Pharmacist, Public Health and Meta-Researcher"
url: "https://deinusername.github.io"
baseurl: ""   # leer lassen bei user.github.io

# Minima-Theme aktivieren
theme: minima

# Navigation im Header explizit definieren (Reihenfolge = MenÃ¼-Reihenfolge)
header_pages:
  - index.md          # about = Startseite
  - pages/publications.md
  - pages/rojects.md
  - pages/teaching.md
  - pages/blog.md
  - pages/services.md
  - pages/about.md
