title: "Martin Haslberger"
description: "Pharmacist, Public Health and Meta-Researcher"
url: "https://deinusername.github.io"
baseurl: ""   # leer lassen bei user.github.io

# Minima-Theme aktivieren
theme: minima

# Navigation im Header explizit definieren (Reihenfolge = MenÃ¼-Reihenfolge)
header_pages:
  - index.md          # about = Startseite
  - publications.md
  - rojects.md
  - teaching.md
  - blog.md
  - services.md
  - about.md
